package com.mycompany.user;

import jakarta.persistence.*;

@Entity
@Table(name = "users")    //use jpi annotation to indicate that this java class is mapped with a table in db
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // meaning that this field will be generated by d automatically

    private Integer id;

    @Column(nullable = false,unique = true , length = 45)
    private String email;

    @Column(length = 15 , nullable = false)
    private String password;

    @Column(length = 45 , nullable = false , name ="first_name")
    private String firstName;

    @Column(length = 45 , nullable = false , name ="last_name")
    private String lastName;

    public boolean isEnabled() {
        return enabled;
    }

    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

    private boolean enabled ;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", email='" + email + '\'' +
                ", password='" + password + '\'' +
                ", firstName='" + firstName + '\'' +
                ", lastName='" + lastName + '\'' +
                '}';
    }
}
